# Generated by Django 3.0.7 on 2020-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangladesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('case', models.BigIntegerField()),
                ('test_case', models.BigIntegerField()),
                ('death', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
            ],
        ),
    ]
