# Generated by Django 3.0.7 on 2020-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bd_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhaka_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('case', models.BigIntegerField()),
            ],
        ),
    ]
