# Generated by Django 3.0.7 on 2020-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dhaka_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bd_gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('case', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
        ),
    ]
